version: "3.5"

services:
  frontend:
    container_name: frontend-local
    image: frontend:latest
    build: ../frontend/web
    ports:
      - 80:80

  postgres_local:
    container_name: postgres-local
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=spring_angular
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data_volume:/var/lib/postgresql/data/pgdata
  
volumes: 
  pg_data_volume:


