version: "3.5"

services:
  frontend:
    container_name: frontend-local
    image: frontend:latest
    build: ../frontend/web
    ports:
      - 80:80

  backend:
    container_name: backend-local
    image: backend:latest
    command: java -jar 
      -Dspring.datasource.url=jdbc:postgresql://postgres-local:5432/spring_angular
      web-1.0.jar
    ports:
      - "8080:8080"

  postgres-local:
    container_name: postgres-local
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=spring_angular
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data_volume:/var/lib/postgresql/data/pgdata
  
volumes: 
  pg_data_volume:


